### ISSUE TITLE
Certificate install fails on windows

### ISSUE THREAD

**Issue by Gymothy** [Yardanico/ai-roguelite-nai#1]
![image](https://user-images.githubusercontent.com/101031660/199157636-e2ff6a55-f7e6-488e-bdbe-4115d4d4f754.png)
Proxier reports that no certificate is found, and running caddy trust manually gives the following

![image](https://user-images.githubusercontent.com/101031660/199157692-8acc23e1-f48b-48aa-9673-2bcc748a2774.png)

**Comment by Yardanico** [comment]
Ah right, this is not related to caddy I think, it's my fault, I forgot to put cacert.pem into the windows archive

**Comment by Yardanico** [comment]
Gonna update it soon, meanwhile you can fix it by downloading https://nim-lang.org/download/dlls.zip and putting cacert.pem from there into the main extracted folder (where the exe files are)

**Comment by Gymothy** [comment]
hey, got around to trying this again. using the certificate, but still not getting any results, no images are showing up.

are these the expected states of both programs after running?

![2022-11-08_00-07-25](https://user-images.githubusercontent.com/101031660/200318373-6662c6f9-54af-47b3-89ac-ac60e4d4f090.png)

**Comment by Yardanico** [comment]
@Gymothy yep, do you have a local webui or NovelAI token for image gen?

**Comment by Gymothy** [comment]
using novelAI - here's my config

![2022-11-08_11-22-34](https://user-images.githubusercontent.com/101031660/200443697-9e0472ba-5c2c-4c71-bff0-9e44ce6b8d46.png)

**Comment by Yardanico** [comment]
@Gymothy can you contact me in Discord at Yardanico#5346 ? That way we can probably solve the issue faster :)

**Comment by Yardanico** [comment]
Solved on Discord - the issue was that I forgot to put instructions regarding getting the NovelAI token
